document.getElementById('year').textContent = new Date().getFullYear();

const physicsFormulas = [
    // List of physics formulas related to finding physical quantities
    "Acceleration due to gravity: g = 9.8 m/s²",
    "Archimedes' Principle: F = ρVg",
    "Bernoulli's Principle: P + 0.5ρv² + ρgh = constant",
    "Boyle's Law: PV = constant",
    "Capacitance: C = Q/V",
    "Coulomb's Law: F = k × (|q<sub>1</sub> × q<sub>2</sub>| / r²)",
    "Density: ρ = m/V",
    "Elastic Potential Energy: U = 0.5 × k × x²",
    "Electric Field: E = F / q",
    "Faraday's Law of Electromagnetic Induction: ε = -dΦ/dt",
    "Fermat's Principle (Optics): δT = 0",
    "Force: F = ma",
    "Frequency: f = 1/T",
    "Gravitational Potential Energy: U = mgh",
    "Hooke's Law: F = -kx",
    "Impulse: I = FΔt",
    "Kinetic Energy: K = 0.5mv²",
    "Magnetic Field: B = μ₀ × (I / 2πr)",
    "Newton's Law of Gravitation: F = (G × m<sub>1</sub> × m<sub>2</sub>) / r²",
    "Ohm's Law: V = IR",
    "Power: P = IV",
    "Pressure: P = F/A",
    "Resistance: R = ρ × (L / A)",
    "Snell's Law: n₁sinθ₁ = n₂sinθ₂",
    "Specific Heat Capacity: c = Q / (m × ΔT)",
    "Speed: v = d/t",
    "Stress: σ = F/A",
    "Temperature Conversion (Celsius to Kelvin): T(K) = T(°C) + 273.15",
    "Torque: τ = r × F × sinθ",
    "Velocity: v = ds/dt",
    "Voltage: V = W/Q",
    "Wave Speed: v = fλ",
    "Work: W = F × d × cosθ",
    // More formulas added alphabetically from here
    "Absorption coefficient: α = -1/d * ln(T)",
    "Alternating current (AC) power: P = Vrms * Irms * cos(θ)",
    "Angular acceleration: α = Δω / Δt",
    "Angular displacement: θ = ω₀t + 0.5αt²",
    "Angular momentum: L = Iω",
    "Angular velocity: ω = Δθ / Δt",
    "Archimedes' principle (buoyant force): F_b = ρ_fluid * V_displaced * g",
    "Atomic number: Z = protons in nucleus",
    "Avogadro's number: N_A = 6.022 × 10²³ mol⁻¹",
    "Bernoulli's equation: P₁ + 0.5ρv₁² + ρgh₁ = P₂ + 0.5ρv₂² + ρgh₂",
    "Biot-Savart law (magnetic field): d𝐁 = μ₀ / 4π * Id𝐥 × r / r³",
    "Bohr radius: a₀ = 0.529 × 10⁻¹⁰ m",
    "Boltzmann constant: k_B = 1.381 × 10⁻²³ J/K",
    "Bouguer's law (light attenuation): I = I₀e^(-μx)",
    "Capacitance (parallel plate capacitor): C = ε₀A / d",
    "Carnot efficiency: η = 1 - T_cold / T_hot",
    "Centripetal acceleration: a_c = v² / r",
    "Centripetal force: F_c = mv² / r",
    "Charge density: ρ = Q / V",
    "Circular motion (period): T = 2πr / v",
    "Coefficient of friction: μ = F_friction / F_normal",
    "Coulomb constant: k_e = 8.987 × 10⁹ Nm²/C²",
    "Critical angle (total internal reflection): sin(critical angle) = n₂ / n₁",
    "Critical temperature (superconductivity): T_c = T₀ * (1 - (T / T_c)³)",
    "Dalton's law (partial pressures): P_total = P₁ + P₂ + ... + P_n",
    "De Broglie wavelength: λ = h / mv",
    "Dielectric constant: ε_r = κ = C / C₀",
    "Diffraction grating (angle): mλ = d sinθ",
    "Doppler effect (frequency): f' = f₀ * (v_sound ± v_observer) / (v_sound ± v_source)",
    "Dulong-Petit law (heat capacity): C = 3R / molar mass",
    "Elastic modulus (Young's modulus): E = stress / strain",
    "Electric dipole moment: p = q * d",
    "Electric field (point charge): E = k_e * |q| / r²",
    "Electric field (uniformly charged rod): E = 2k_e * λ / r",
    "Electric field (uniformly charged sphere): E = k_e * Q / r²",
    "Electric flux: Φ_E = E * A * cosθ",
    "Electric potential (point charge): V = k_e * q / r",
    "Electric potential (uniformly charged rod): V = 2k_e * λ * ln(R_final / R_initial)",
    "Electric potential (uniformly charged sphere): V = k_e * Q / r",
    "Electromagnetic wave speed: c = 1 / sqrt(μ₀ * ε₀)",
    "Electron charge: e = -1.602 × 10⁻¹⁹ C",
    "Elementary charge: e = 1.602 × 10⁻¹⁹ C",
    "Energy (mass-energy equivalence): E = mc²",
    "Escape velocity: v_escape = sqrt(2GM / r)",
    "Fermi energy level: E_F = (h² / 2m)(3N / 8πV)^(2/3)",
    "Fizeau experiment (speed of light in medium): v = c / n",
    "Fluid dynamics (Bernoulli's equation): P + 0.5ρv² + ρgh = constant",
    "Flux (magnetic flux): Φ_B = B * A * cosθ",
    "Fourier's law (heat conduction): q = -kA * (dT / dx)",
    "Frequency (period): f = 1 / T",
    "Friction force (Coulomb): F_friction = μ * F_normal",
    "Frictional torque: τ_friction = r * F_friction * sinθ",
    "Gas law (ideal gas law): PV = nRT",
    "Geiger counter (radioactive decay): N = N₀ * e^(-λt)",
    "Gravitational field strength: g = GM / r²",
    "Half-life (radioactive decay): t_(1/2) = ln(2) / λ",
    "Heat capacity (constant pressure): C_p = ΔQ / ΔT",
    "Heat capacity (constant volume): C_v = ΔQ / ΔT",
    "Heat conduction (Fourier's law): q = -kA * (dT / dx)",
    "Heat engine (efficiency): η = 1 - (T_cold / T_hot)",
    "Helmholtz free energy: A = U - TS",
    "Hertz (frequency): 1 Hz = 1 cycle per second",
    "Hubble's law (expanding universe): v = H₀ * d",
    "Hydrostatic pressure: P = ρgh",
    "Impulse (change in momentum): I = FΔt",
    "Inclined plane (force): F_parallel = mg sinθ",
    "Inclined plane (work): W = mg cosθ * d",
    "Induced electromotive force (emf): ε = -dΦ_B / dt",
    "Inductance (self-inductance): L = Φ_B / I",
    "Inertia (moment of inertia): I = Σmr²",
    "Intensity (sound): I = P / A",
    "Internal energy (first law of thermodynamics): ΔU = Q - W",
    "Isobaric process (constant pressure): Q = ΔU + W",
    "Isochoric process (constant volume): Q = ΔU",
    "Isothermal process (constant temperature): ΔU = 0",
    "Joule (energy): 1 J = 1 kg * m²/s²",
    "Kepler's first law (elliptical orbits): The path of each planet around the Sun is an ellipse with the Sun at one focus.",
    "Abbe number: V_d = (n_D - 1) / (n_F - n_C)",
    "Absorption coefficient: α(λ) = 4πκ(λ) / λ",
    "Angle of deviation (prism): Δθ = A - (A₀ + A' - A'₀)",
    "Angle of incidence: θ_i",
    "Angle of refraction: θ_r",
    "Antireflection coating (thin film): δ = (λ / 4) * (n₂ - n₁)",
    "Aperture (numerical): NA = n sinθ",
    "Aplanatic point: (n₁ / r₁) + (n₂ / r₂) = 0",
    "Arago spot (poisson spot): X = R * (2n + 1)λ / 4a",
    "Astigmatism: φ = -δ / 2 * (1 / r₁ - 1 / r₂)",
    "Attenuation coefficient: α = 4πκ / λ",
    "Babinet-Soleil compensator: δ = (λ / 2) * (n₂ - n₁)",
    "Babinet's principle: I = I₀ * cos²(θ)",
    "Band gap energy: E_g = hv = hc / λ",
    "Bézier's condition: (n₁ / r₁) + (n₂ / r₂) = 0",
    "Biot-Savart law (magnetic field): d𝐁 = μ₀ / 4π * Id𝐥 × r / r³",
    "Birefringence (double refraction): Δn = n₁ - n₂",
    "Brewster's angle: θ_B = tan⁻¹(n₂ / n₁)",
    "Brightness (luminance): B = I / A",
    "Cassegrain telescope: f₀ = f * (1 + d/f)",
    "Cauchy's equation: n = A + (B / λ²) + (C / λ⁴)",
    "Chromatic aberration: δ = (n_D - n_C) * f * (A / 2) * (n_C + n_D - 2n) / f₀",
    "Coherence length: L_c = λ² / Δλ",
    "Collimator (optical): f_c = f * (1 + d/f)",
    "Colour temperature: T = 1 / λ_max",
    "Compound microscope: m = f / f₀ * d",
    "Confocal microscope: l = d₁ * d₂ / l",
    "Conjugate points: m = -p / q",
    "Conservation of energy: I = I₀ * cos²(θ)",
    "Critical angle (total internal reflection): θ_c = n₂ / n₁",
    "Crystal optics (Brewster's angle): θ_B = tan⁻¹(n₂ / n₁)",
    "Curvature (radius of): R = n",
    "Degree of transparency: T = 1 - R",
    "Diffraction grating (angle): mλ = d sinθ",
    "Dispersion (prism): d = λ / 2(n₂ - n₁)",
    "Diverging lens: F = f",
    "Eikonal equation: n = A + (B / λ²) + (C / λ⁴)",
    "Einstein coefficients: B_i = C_iA_i",
    "Electric field: E = E₀ * sin(2πft)",
    "Electromagnetic radiation: S = 2E₀ / (μ₀c²)",
    "Electromagnetic wave speed: c = 1 / sqrt(μ₀ * ε₀)",
    "Emulsification: D = 4λ / d",
    "Evanescent wave: L = c² / μ₀ * E₀ * B₀",
    "Fermat's principle (optics): δT = 0",
    "Fibre optics (numerical aperture): θ_i = n sinθ",
    "Focal length: f = R / n",
    "Focal point (conjugate points): m = -p / q",
    "Focusing (depth of): δ = t/ 2 * n sinθ",
    "Fresnel lens: f = R / n",
    "Fresnel's equation: δ = (n_d - n_c) * f * (A / 2) * (n_c + n_d - 2n) / f₀",
    "Fresnel's law: θ = n sin(θ_i) - n sin(θ_r)",
    "Gabor's hologram: D = 4λ / d",
    "Geometric optics: θ = (n₁ / r₁) + (n₂ / r₂) = 0",
    "Grating (diffraction): m = d sinθ",
    "Grazing incidence: δ = (n₂ - n₁) * f * (A / 2) * (n₁ + n₂ - 2n) / f₀",
    "Heisenberg uncertainty principle: Δx * Δp ≥ h / 2π",
    "Hertz (frequency): 1 Hz = 1 cycle per second",
    "Holographic recording: I = I₀ * cos(2πft)",
    "Huygens' principle: θ = λ / 2(n₂ - n₁)",
    "Hyperopia (farsightedness): f = R / n",
    "Impedance: Z = √(R² + (ωL - 1 / ωC)²)",
    "Infrared spectroscopy: E = E₀ * sin(2πft)",
    "Intensity (optical): I = I₀ * cos²(θ)",
    "Interference (fringe spacing): λ = d sinθ",
    "Iris (aperture): NA = n sinθ",
    "Lambert's law (absorption): A = 0.5I₀ * e^(-μx)",
    "Laser (semiconductor): δ = (λ / 4) * (n₂ - n₁)",
    "Lens (equation): 1/f = (n₂ - n₁) * (1 / R₁ - 1 / R₂)",
    "Luminance (brightness): B = I / A",
    "Magnification (angular): M = δt / dt",
    "Magnetism (electromagnetic wave): θ = n sinθ - n sin(θ_i)",
    "Magnetic field: B = μ₀ * (I / 2πr)",
    "Magnetic force: F = B * I * L",
    "Maxwell's equations: μ = μ₀ * (I / 2πr)",
    "Michelson interferometer: E = E₀ * cos(2πft)",
    "Microscope (compound): m = f / f₀ * d",
    "Microscope (confocal): l = d₁ * d₂ / l",
    "Monochromatic aberration: δ = (n₂ - n₁) * f * (A / 2) * (n₁ + n₂ - 2n) / f₀",
    "Newton's rings: D = 4λ / d",
    "Newton's third law (force): F = F₀ * cos²(θ)",
    "Normal (angle): θ = n sinθ - n sin(θ_i)",
    "Objective lens: f = R / n",
    "Opacity (degree of): T = 1 - R",
    "Optical coherence tomography: L_c = λ² / Δλ",
    "Optical density: α = -1 / d * ln(T)",
    "Optical path difference: mλ = d sinθ",
    "Optical rotation (polarimetry): θ = n sinθ - n sin(θ_i)",
    "Optics (geometric): θ = (n₁ / r₁) + (n₂ / r₂) = 0",
    "Pellin-Broca prism: δ = (λ / 2) * (n₂ - n₁)",
    "Periscope: f = R / n",
    "Photon energy: E = hν = hc / λ",
    "Photoelasticity: Δσ = A - (A₀ + A' - A'₀)",
    "Photographic exposure: D = 4λ / d",
    "Photometry (luminous intensity): B = I / A",
    "Polarisation (angle): θ = n sinθ - n sin(θ_i)",
    "Polarising angle: θ_B = tan⁻¹(n₂ / n₁)",
    "Polarized light: δ = (λ / 2) * (n₂ - n₁)",
    "Prism (angle of deviation): Δθ = A - (A₀ + A' - A'₀)",
    "Pupil (aperture): NA = n sinθ",
    "Quantum mechanics: Δx * Δp ≥ h / 2π",
    "Radiation (electromagnetic): S = 2E₀ / (μ₀c²)",
    "Radioactivity (half-life): t_(1/2) = ln(2) / λ",
    "Action (quantum): S = ∫Ldt = 2πħn",
    "Annihilation operator: a|n⟩ = √n|n-1⟩",
    "Angular momentum: L = r × p = mvr = ħl(l + 1)",
    "Anticommutation relation: {A,B} = AB + BA",
    "Atom (hydrogen energy levels): E_n = -13.6eV/n²",
    "Atomic number: Z = protons in nucleus",
    "Atomic orbital (angular momentum): L = r × p = mvr = ħl(l + 1)",
    "Atomic physics (Bohr model): E_n = -13.6eV/n²",
    "Atomic radius (Bohr model): r_n = n²ħ² / (Zke²m)",
    "Atomic unit of energy: E_h = 4.3597 × 10⁻¹⁸ J",
    "Atomic unit of length: a₀ = 0.529 × 10⁻¹⁰ m",
    "Atomic unit of time: τ = 2.418 × 10⁻¹⁷ s",
    "Atomic unit of velocity: v₀ = 2.187 × 10⁶ m/s",
    "Barrier penetration probability: T = e⁻²κd",
    "Barrier potential (quantum tunneling): V₀ = E - U₀",
    "Beta decay (energy): Q = M(P) - M(D) - M(ν)",
    "Boltzmann constant: k_B = 1.381 × 10⁻²³ J/K",
    "Born approximation (scattering): f = -2πμr(θ) / ħ²",
    "Bose-Einstein condensate: N = (exp(E - μ) / kT) - 1",
    "Cavity quantum electrodynamics: g = √(ω/2ε₀V)",
    "Charge density: ρ = Q / V",
    "Commutator (operator): [A,B] = AB - BA",
    "Complex wavefunction: ψ = e⁻ⁱˣ",
    "Compton wavelength: λ_C = h / mc",
    "Conservation laws (quantum): ΔQ = ΔE = Δp = Δt",
    "Coordinate representation (wavefunction): ψ(x) = ∫ψ*(x)ψ(x)d³x",
    "Correlation function: G(r) = ∫dΩP(r,Ω)",
    "Critical temperature (superconductivity): T_c = T₀(1 - (T/T_c)³)",
    "Cross section (scattering): σ = λ² / 4π",
    "Cutoff frequency (Planck): ν_c = E/6.626 × 10⁻³⁴ J.s",
    "De Broglie wavelength: λ = h / mv",
    "Density matrix (quantum mechanics): ρ = |ψ⟩⟨ψ|",
    "Density of states: g(E) = (E - E_F) / ΔE",
    "Dirac equation: (γᵤpᵥ - mc)Ψ = 0",
    "Discrete spectrum (quantum mechanics): E_n = -13.6eV/n²",
    "Doppler effect (frequency): f' = f₀(v_sound ± v_observer) / (v_sound ± v_source)",
    "Duality (wave-particle): p = h / λ",
    "Eigenvalue (operator): A|a⟩ = a|a⟩",
    "Eigenfunction (operator): A|a⟩ = a|a⟩",
    "Ehrenfest theorem: ΔxΔp - h/2π",
    "Electric dipole moment: p = qd",
    "Electric field (point charge): E = k_e(q / r²)",
    "Electric field (uniformly charged rod): E = 2k_eλ / r",
    "Electric field (uniformly charged sphere): E = k_eQ / r²",
    "Electric flux: Φ_E = EAcosθ",
    "Electric potential (point charge): V = k_eq / r",
    "Electric potential (uniformly charged rod): V = 2k_eλln(R_final / R_initial)",
    "Electric potential (uniformly charged sphere): V = k_eQ / r",
    "Electromagnetic wave speed: c = 1 / √(μ₀ε₀)",
    "Electron charge: e = -1.602 × 10⁻¹⁹ C",
    "Elementary charge: e = 1.602 × 10⁻¹⁹ C",
    "Energy levels (hydrogen atom): E_n = -13.6eV/n²",
    "Entanglement (quantum): Ψ = (|1⟩⊗|1⟩ + |2⟩⊗|2⟩ + |3⟩⊗|3⟩)/√3",
    "Exchange symmetry: Ψ = (A + B) - (B + A)",
    "Expectation value (quantum mechanics): ⟨A⟩ = ⟨a|A|a⟩",
    "Exclusion principle (Pauli): Ψ = (|1⟩⊗|1⟩ - |2⟩⊗|2⟩)",
    "Faraday's law (quantum electrodynamics): dΦ/dt",
    "Fermat's principle (quantum mechanics): δT = 0",
    "Fermi energy level: E_F = (h² / 2m)(3N / 8πV)^(2/3)",
    "Fermion operators: a|n⟩ = √n|n-1⟩",
    "Fermionic statistics: A|a⟩ = -a|a⟩",
    "Fine structure constant: α = e² / ħc",
    "Flux quantization: Φ₀ = h / 2e",
    "Fourier's law (quantum): q = -kA(dT / dx)",
    "Frequency (quantum mechanics): f = 1 / T",
    "Fusion (nuclear): M = M(P) - M(D) - M(ν)",
    "Gamma decay (energy): Q = M(P) - M(D) - M(ν)",
    "Gauge theory (quantum): ψ = e⁻ⁱˣ",
    "Gravitational field strength: g = GM / r²",
    "Half-life (radioactive decay): t_(1/2) = ln(2) / λ",
    "Hamiltonian operator: H|ψ⟩ = E|ψ⟩",
    "Harmonic oscillator: E = (n + 1/2)ħω",
    "Heisenberg uncertainty principle: ΔxΔp ≥ h / 2π",
    "Hertz (frequency): 1 Hz = 1 cycle per second",
    "Hubble's law (expanding universe): v = H₀d",
    "Hydrostatic pressure: P = ρgh",
    "Induced electromotive force (emf): ε = -dΦ/dt",
    "Infinite potential well: E_n = (n²π²ħ²) / 2mL²",
    "Infrared spectroscopy: E = E₀sin(2πft)",
    "Intensity (quantum mechanics): I = I₀cos²(θ)",
    "Interference (fringe spacing): λ = d sinθ",
    "Isobaric process (quantum mechanics): Q = ΔU + W",
    "Isochoric process (quantum mechanics): Q = ΔU",
    "Isothermal process (quantum mechanics): ΔU = 0",
    "Joule (energy): 1 J = 1 kgm²/s²",
    "Kepler's first law (elliptical orbits): θ = λ² / 4π",
    "Klein-Gordon equation: (□ + m²)Ψ = 0",
    "Kinetic energy (quantum mechanics): K = (1 / 2)mv²",
    "Lamb shift (atomic physics): ΔE = E_F - E₀",
    "Larmor precession (magnetic resonance): Ω₀ = -gµB/h",
    "Laser (semiconductor): δ = (λ / 4) * (n₂ - n₁)",
    "Lattice constant: a = 2r",
    "Lattice energy: U = 1 / 2 C₁C₂ / r",
    "Legendre transform (quantum mechanics): F = G - TS",
    "Length contraction: L = c / √(μ₀ε₀)",
    "Light (electromagnetic wave): E = E₀sin(2πft)",
    "Lorentz force (electromagnetic wave): θ = n sinθ - n sin(θ_i)",
    "Magnetic field (quantum mechanics): B = µ₀(I / 2πr)",
    "Magnetic force (quantum mechanics): F = BIL",
    "Magnetic resonance (magnetic field): θ = n sinθ - n sin(θ_i)",







]






const formulasSection = document.getElementById('formulas');
const searchInput = document.getElementById('searchInput');

// Function to display all formulas
function displayFormulas() {
    formulasSection.innerHTML = '';
    physicsFormulas.forEach(formula => {
        const formulaHTML = `<div class="formula"><p>${formula}</p></div>`;
        formulasSection.innerHTML += formulaHTML;
    });
}

// Function to filter formulas based on search input
function filterFormulas(searchTerm) {
    formulasSection.innerHTML = '';
    physicsFormulas.forEach(formula => {
        if (formula.toLowerCase().includes(searchTerm.toLowerCase())) {
            const formulaHTML = `<div class="formula"><p>${formula}</p></div>`;
            formulasSection.innerHTML += formulaHTML;
        }
    });
}

// Initial display of all formulas
displayFormulas();

// Event listener for search input
searchInput.addEventListener('input', () => {
    const searchTerm = searchInput.value.trim();
    if (searchTerm !== '') {
        filterFormulas(searchTerm);
    } else {
        displayFormulas();
    }
});
